dist: trusty
sudo: false

language: python

addons:
    apt:
        packages:
            - texlive-base
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - latex-xcolor
            - pgf
            - dvipng
            - dvidvi

env:
- LATEX_INTERACTION_MODE="-interaction=nonstopmode"

## Check that the documentation compiles correctly
script:
    - cd latex
    - make all
    - cd ..
