# Configuration for readthedocs
# See https://docs.readthedocs.io/en/latest/yaml-config.html
#
# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-3.12-24.1" # note that libmamba-solver is available since 22.1
  jobs:
    post_create_environment:
      - python -m pip install --exists-action=w --no-cache-dir -r requirements.txt
      - rabbitmq-server -detached
      - sleep 10
      - rabbitmq-diagnostics status
      - verdi presto
      - verdi daemon start
      - verdi status
      - aiida-pseudo install sssp -x PBEsol
      - verdi group list
      - cat /proc/cpuinfo | grep processor | wc -l

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

# Disabling all unneeded formats (note that HTML and JSON are always built)
# See https://docs.readthedocs.io/en/latest/yaml-config.html#formats
formats: []

conda:
  environment: environment.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
