# Configuration for readthedocs
# See https://docs.readthedocs.io/en/latest/yaml-config.html
#
# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py


# Disabling all unneeded formats (note that HTML and JSON are always built)
# See https://docs.readthedocs.io/en/latest/yaml-config.html#formats 
formats: []

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
