remote_theme: aiidateam/jekyll-theme-slate
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    default_lang: python
#    css_class: 'highlight'
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#highlighter: pygments 
plugins:
  - jekyll-sitemap

baseurl: /aiida-tutorials
url: https://ltalirz.github.io
