.. # define a hard line break for HTML
.. |br| raw:: html

   <br />

.. # Define a time icon
.. |time| image:: /_static/time.png
    :width: 15px

.. # Define a Python icon
.. |python| image:: /_static/python.png
    :width: 15px

.. # Define an AiiDA icon
.. |aiida| image:: /_static/aiida_logo.png
    :width: 15px

.. # define level colors
.. role:: aiida-green
.. role:: aiida-blue
.. role:: aiida-orange
