name: aiida-environment
channels:
  - conda-forge
dependencies:
  # to convert markdown files to notebooks
  - jupytext==1.5.0
  - myst-parser==0.8.2
  # aiida environment
  - aiida-core==1.2.1
  - aiida-core.services==1.2.1
