name: continuous-integration

on:
  push:
    # only pushes to main trigger
    branches: [main]
  pull_request:
    # always triggered

jobs:

  pre-commit:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - uses: pre-commit/action@v2.0.0

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge, defaults
        environment-file: environment.yml
        python-version: "3.11"
        auto-activate-base: true
        activate-environment: true
    - name: "Build HTML docs"
      run: |
        make -C docs html linkcheck
      env:
        SPHINXOPTS: -nW --keep-going
